const G_ACTORS_MAP = {};
const G_initActors = () => {
  G_ACTORS_MAP['1,1,10,15'] = G_CHARACTER_OLD_MAN;
  G_ACTORS_MAP['1,1,11,11'] = G_CHARACTER_STATUE_THINKER;
  G_ACTORS_MAP['1,1,6,15'] = G_CHARACTER_STATUE_RUNNER;
  G_ACTORS_MAP['1,1,4,9'] = G_CHARACTER_STATUE_SPEAKER;
  G_ACTORS_MAP['0,1,9,15'] = G_SIGN_POT_ROOM;
};
